#!/bin/bash
#NAMESPACE=route_admin

dependencies::depends "http/webauth"
dependencies::depends "timeslots/timeslots"
dependencies::depends "views/admin"
dependencies::depends "queue/client"

function headers() {
# nothing
}

function show() {
    if [[ `webauth::has_role ROLE_ADMIN` -ne 1 ]];
    then
        http::header "Status" "403 Forbidden"
        echo "Access denied"
        return
    fi
    
    local queue=`http::get_param queue | http::strip_all`
    if [[ `radio_timeslots::get_all_queues | grep -c "$queue"` -ne 1 ]]; then
        http::header "Status" "404 Not sure what you looking for"
        echo "Not sure what you looking for"
        return
    fi
    
    local remove=`http::get_post itm_remove | http::strip_all`
    if [[ $remove != "" ]]; then
        queue_client::delete "$queue" "$remove" 99999
        logger::log "info" "$remove deleted from $queue"
    fi
    
    local to_queue=`http::get_post to_queue | http::strip_all`
    if [[ $to_queue != "" ]]; then
        if [[ `radio_timeslots::get_all_queues | grep -c "$to_queue"` -ne 1 ]]; then
            http::header "Status" "404 Not sure what you looking for"
            echo "Not sure what you looking for"
            return
        fi
        queue_client::publish "$to_queue" "$remove"
        logger::log "info" "$remove added to $to_queue"
    fi

    view_admin::show "$queue" "`queue_client::peek_multiple $queue 0 9999`"
}
