#!/bin/bash
#NAMESPACE=route_ajax

dependencies::depends "http/http"
dependencies::depends "http/webauth"

function headers() {
    http::set_header "Content-Type" "text/html"
}

function timer() {
    echo `cat /volatile/ffout | tr "\r" "\n" | tail -n 1 | cut -d= -f3 | cut -d\  -f1` / `cat $SHARED_STORAGE/current_meta | cut -d\: -f2- | cut -d, -f1 | sed -e 's/[hms]//g'`
}

function current_id() {
    cat $SHARED_STORAGE/current_id
}