#!/bin/bash
#NAMESPACE=route_skip

dependencies::depends "http/http"
dependencies::depends "http/webauth"
dependencies::depends "coolcat/coolcat"
dependencies::depends "queue/client"

function headers() {
    http::set_header "Content-Type" "text/html"
    if [[ `webauth::is_authorized` -gt 0 ]]
    then
	http::set_header "Status" "200"
	http::set_header "Refresh" "1; url=$BASE_DIR/app.sh?route=default"
    else
        http::set_header "Status" "403"
    fi
}

function show() {
    if [[ `coolcat::is_cool` -lt 1 ]]                                                                                                                                                                                                                                                                                                                                      
    then                                                                                                                                                                                                                                                                                                                                                                   
	echo "Sorry, your coolcat status does not allow you to do that"                                                                                                                                                                                                                                                                                                    
	return 1                                                                                                                                                                                                                                                                                                                                                           
    fi
  
    if [[ `webauth::is_authorized` -gt 0 ]]
    then
	if [[ `http::get_post remove` -eq 1 ]]
	then
	    queue_client::publish command-queue "skip-remove"
	else
	    queue_client::publish command-queue "skip"
	fi
	coolcat::coolcat_action
    else 
	echo "LOL NO"
    fi
}