#!/bin/bash
#NAMESPACE=route_add

dependencies::depends "http/http"
dependencies::depends "http/webauth"
dependencies::depends "coolcat/coolcat"
dependencies::depends "queue/client"
dependencies::depends "timeslots/timeslots"

function headers() {
    http::set_header "Content-Type" "text/html"
    if [[ `webauth::is_authorized` -gt 0 ]]
    then
	http::set_header "Status" "201"
	http::set_header "Refresh" "1; url=$BASE_DIR/app.sh?route=default"
    else
        http::set_header "Status" "403"
	return 1
    fi

    if [[ `coolcat::is_cool` -lt 1 ]]
    then
        http::set_header "Status" "403"
    fi
}

function add_file() {
    if [[ `webauth::is_authorized` -lt 1 ]]
    then
	echo "LOL NO"
	return 1
    fi
    
    if [[ `coolcat::is_cool` -lt 1 ]]
    then
	echo "Sorry, your coolcat status does not allow you to do that"
	return 1
    fi    

    file_name=`http::get_file newfile`
    if [[ `http::get_mimetype $file_name | egrep -c "^audio/*"` -lt 0 ]]
    then 
	return 1
    fi
    new_file_name=cust`http::get_original_filename $file_name | tr -d '.' | tr -d '/' | tr -d '\' | tr -d "\n" | tr -d "\r" | tr -d "(" | tr -d ")" | tr -d " "`
    cp $file_name $SHARED_STORAGE/cache/$new_file_name #FIXME: ugly hack, should use $YTDL_CACHE_DIR
    if [[ $? -eq 0 ]]
    then
	this::queue $new_file_name
    fi
}

function show() {
    if [[ `coolcat::is_cool` -lt 1 ]]
    then
	echo "Sorry, your coolcat status does not allow you to do that"
	return 1
    fi    

    if [[ `webauth::is_authorized` -gt 0 ]]
    then
	local id=`http::get_post ytid | sed 's/[^a-zA-Z0-9.,:;!?@~#$%^&*()+-_]//g'`
	if [[ `echo $id | grep 'list' -c` -gt 0 ]]
	then
	    echo "let's not upload lists OK? JUST ID PLOX";
	fi
	echo $id;
	if [[ $id == "" ]]
	then
        echo "where id at"
	    return 1
	fi
	this::queue $id
    else 
	echo "LOL NO"
    fi
}

function queue(id) {
    if [[ "`http::get_post order`" == "L" && `webauth::has_role ROLE_ADD_TO_CUST_QUEUE` -eq 1 ]]; then
        queue_client::publish_left "`this::_get_queue`" "$id"
    else
        queue_client::publish "`this::_get_queue`" "$id"
    fi
    if [[ `webauth::has_role ROLE_FOREVER_COOL` -ne 1 ]]; then
        coolcat::coolcat_action
    fi
}

function _get_queue() {
    local queue=`http::get_post to_queue | sed 's/[^a-zA-Z0-9.,:;!?@~#$%^&*()+-_ ]//g'`
    if [[ `radio_timeslots::get_all_queues | grep -c "$queue"` -ne 1 || `webauth::has_role ROLE_ADD_TO_CUST_QUEUE` -ne 1 ]]; then
        echo "$REQUEST_QUEUE"
        return
    fi
    echo $queue
}
