#!/bin/bash
#NAMESPACE=route_skip

dependencies::depends "http/http"
dependencies::depends "http/webauth"
dependencies::depends "coolcat/coolcat"

function headers() {
    http::set_header "Content-Type" "text/html"
    if [[ `webauth::is_authorized` -gt 0 ]]
    then
	http::set_header "Status" "200"
	http::set_header "Refresh" "1; url=/cgi-bin/v2/app.sh?route=default"
    else
        http::set_header "Status" "403"
    fi
}

function show() {
    if [[ `coolcat::is_cool` -lt 1 ]]                                                                                                                                                                                                                                                                                                                                      
    then                                                                                                                                                                                                                                                                                                                                                                   
	echo "Sorry, your coolcat status does not allow you to do that"                                                                                                                                                                                                                                                                                                    
	return 1                                                                                                                                                                                                                                                                                                                                                           
    fi
  
    if [[ `webauth::is_authorized` -gt 0 ]]
    then
	if [[ `http::get_post remove` -eq 1 ]]
	then
	    amqp-publish -u amqp://rabbits:rabbits@rabbits:5672 -e command-queue -r command-queue -p -b "skip-remove"
	    redis-cli -h redis --raw decr songcounter
	else
	    amqp-publish -u amqp://rabbits:rabbits@rabbits:5672 -e command-queue -r command-queue -p -b "skip"
	fi
	coolcat::coolcat_action
    else 
	echo "LOL NO"
    fi
}