#!/bin/bash
#NAMESPACE=view_scripts

dependencies::depends "http/webauth"
dependencies::depends "routes/route_ajax"
dependencies::depends "coolcat/coolcat"
dependencies::depends "timeslots/timeslots"

function show() {
cat << JSCODE
    <script type=text/javascript>
    `cat $DIR/data/scripts.js`
    </script>
JSCODE
}
