#!/bin/bash
#NAMESPACE=coolcat

dependencies::depends "http/webauth"

function is_cool() {
    if [[ `webauth::is_authorized` -lt 1 ]]
    then
	echo 0
	return 3
    fi

    if [[ `webauth::session_time` -lt $COOLCAT_TIME ]]
    then
	echo 0
	return 2
    fi


    if [[ `this::coolcat_action_count` -gt $COOLCAT_AMOUNT ]]
    then
	echo 0
	return 1
    fi
    
    echo 1
    return 0
}

function cat_coolness() {
    if [[ `this::is_cool` -lt 1 ]]
    then
	this::is_cool > /dev/null
	if [[ $? -eq 2 ]]
	then 
	    echo "not cool YET"
	else
	    echo "not cool"
	fi
	return 1
    fi

    if [[ `this::coolcat_action_count` -lt `expr $COOLCAT_AMOUNT / 3` ]]
    then
	echo "relaxed"
	return 0
    fi

    if [[ `this::coolcat_action_count` -lt `expr $COOLCAT_AMOUNT / 2` ]]
    then
	echo "warm"
	return 0
    fi

    if [[ `this::coolcat_action_count` -gt `expr $COOLCAT_AMOUNT / 2` ]]
    then
	echo "sweaty"
	return 0
    fi
    echo "cool"
    return 0
}

function coolcat_action_count() {
    local id=`webauth::getid`
    redis-cli --raw -h redis get "$id:added"
}

function coolcat_action() {
    redis-cli --raw -h redis incr "`webauth::getid`:added" > /dev/null
    redis-cli --raw -h redis expire "`webauth::getid`:added" $COOLCAT_TIME  > /dev/null
}